name: Build and Deploy a Container

on:
  pull_request:
    branches: [ develop ]
  push:
    branches:
      - develop

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
  SERVICE: example-app
  REGION: asia-northeast1
  IMAGE: gcr.io/${{ secrets.GCP_PROJECT }}/example-app:${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          # ref:https://dev.classmethod.jp/articles/google-cloud-auth-with-workload-identity/
          workload_identity_provider: "projects/934369182340/locations/global/workloadIdentityPools/my-pool"
          service_account: "934369182340-compute@developer.gserviceaccount.com"

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: goodboop86/prefect:latest
          secrets: |
            "my_env1=${{ secrets.PREFECT_API_KEY }}"

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0.4.0
        with:
          service: ${{ env.SERVICE }}
          image: ${{ env.IMAGE }}
          region: ${{ env.REGION }}