name: Build and Deploy a Container

on:
  pull_request:
    branches: [ develop ]
  push:
    branches:
      - develop

permissions:
  contents: read
  pull-requests: write

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
  SERVICE: youtube_upload
  REGION: asia-northeast1
  IMAGE: gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.SERVICE }}:${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: auth
        uses: 'google-github-actions/auth@v0.4.1'
        with:
          # ref:https://dev.classmethod.jp/articles/google-cloud-auth-with-workload-identity/
          workload_identity_provider: "projects/934369182340/locations/global/workloadIdentityPools/my-pool/providers/my-provider"
          service_account: "934369182340-compute@developer.gserviceaccount.com"

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: goodboop86/prefect:latest
          secrets: |
            "my_env1=${{ secrets.PREFECT_API_KEY }}"

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v0.4.0
        with:
          service: ${{ env.SERVICE }}
          image: ${{ env.IMAGE }}
          region: ${{ env.REGION }}